server:
  port: 8001

spring:
  application:
      name: vservice-eureka-dev1


eureka:
  instance:
    hostname: eureka-dev1
    instance-id: http://localhost:${server.port}
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8002/eureka/
  server:
    #保护模式
    enable-self-preservation: true
    #清理无效服务时间 默认60秒
    eviction-interval-timer-in-ms: 10000

